flbook/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView, search

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('search', search, name='search'),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, 
    invites_received_view, 
    invite_profiles_list_view,
    # profiles_list_view, 
    ProfileListView,
    ProfileDetailView,
    send_invitations,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    # path('all-profiles/', profiles_list_view, name='all-profiles-view'),
    path('send-invite/', send_invitations, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', accept_invitation, name='accept-invite'),
    path('my-invites/reject/', reject_invitation, name='reject-invite'),
]

profiles/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User

from .utils import get_random_code # For slug field
from django.template.defaultfilters import slugify

from django.db.models import Q
# Create your models here.

'''
Django Model Manager  -- Manager is responsible for the communication with the database 

While creating queryset we use objects as the default model Manager for each model. But we can extended it
very easy to organise our code just a little bit better. We will do it with the help of custom Manager.

With the help of the custom Manager we are going to get invitations received from different users all the
profiles in our system excluding of course ourselves. And finally all the profiles that we can invite to
our friends.

Create RelationshipManager class and in order to have RelationshipManager working need to write 
objects = RelationshipManager() inside Relationship model. Then create views, url and templates for this.


Create ProfileManager class and in order to have ProfileManager working write objects = ProfileManager()
inside Profile model. Then create views, url and templates for this.
'''

class ProfileManager(models.Manager):
    # Get all the profiles whom I can send invites.
    def get_all_profiles_to_invite(self, sender): # sender because we need to know who is the sender.
        profiles = Profile.objects.all().exclude(user=sender)  # sender from Relationship model. And excluding our own.
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = set([])  # It will take unique and will not take duplicate value/users. For this set, we will use add() instead of append()
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver) # instead of append() write add() for set in empty list.
                accepted.add(rel.sender)
        print(accepted)

        available = [profile for profile in profiles if profile not in accepted] # List comprehension. List of all the available profile to invite.
        print(available)
        return available

    def get_all_profiles(self, me): # Get all the profiles which are available excluding me.
        profiles = Profile.objects.all().exclude(user=me) # Excluded by user field from Profile model and user is set to me.
        return profiles

class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Every user will have only his own profile.
    bio = models.TextField(default='No bio ....', max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/') # Create media_root folder within static_cdn. Put a avatar.png within media_root folder.
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        # return f'{self.user.username}-{self.created}'
        return f'{self.user.username}-{self.created.strftime("%d-%m-%Y")}'

    def get_absolute_url(self):
        return reverse('profiles:profile-detail-view', kwargs={'slug': self.slug})

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()  # posts is the related_name from author field of Post model. Also we can use modelname_set.

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()  # modelname_set. relationship with post field of like model.
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked +=1
        return total_liked

    def get_likes_received_no(self):
        posts = self.posts.all()  # posts is the related_name of author field of Post model.
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    ##--## Slug Start ##--##

    __initial_first_name = None
    __initial_last_name = None
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):  # For random slug field, created get_random_code function into utils.py file.
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == '':
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + '' + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + '' + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)
    
    ##--## Slug End ##--##



STATUS_CHOICES = (   # for status field. 
    ('send', 'send'),
    ('accepted', 'accepted'),
)

class RelationshipManager(models.Manager):
    # This will give us all the invitations that we received from different users.
    def invitations_received(self, receiver): # receiver is the ForeignKey(to the Profile) field of Relationship model.
        qs = Relationship.objects.filter(receiver=receiver, status='send') # receiver(first one) that is we pass over here.
        return qs

    # Relationship.objects.invitations_received(myprofile)  # All the relationship received for this particular profile.


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager() # Extends our existing manager.

    def __str__(self):
        return f'{self.sender}-{self.receiver}-{self.status}'

profiles/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None ,instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }
    return render(request, 'profiles/myprofile.html', context)


@login_required
def invites_received_view(request):  # Others user when send me a request.
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(profile)  # Geeting all the invitations for this particular profile. invitations_received function from model Manager.

    results = list(map(lambda x: x.sender, qs)) # To see only the senders. If we pass qs only then we will see the receiver also.
    is_empty = False
    if len(results) == 0:
        is_empty = True
    
    context = {
        'qs': results,
        'is_empty': is_empty,
    }
    return render(request, 'profiles/my_invites.html', context)


@login_required
def accept_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk') # Graving the pk.
        sender = Profile.objects.get(pk=pk) # Get sender by the pk
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my-invites-view')


@login_required
def reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk') # Graving the pk.
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my-invites-view')


@login_required
def invite_profiles_list_view(request): # The list of the profiles whom I can send invites.
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)

    context = {
        'qs': qs,
    }
    return render(request, 'profiles/to_invite_list.html', context)



# def profiles_list_view(request): # All the profiles.
#     user = request.user
#     qs = Profile.objects.get_all_profiles(user)

#     context = {
#         'qs': qs,
#     }
#     return render(request, 'profiles/profile_list.html', context)



class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    context_object_name = 'qs' # Also we can use object_list as context instead of qs by default.

    def get_queryset(self): # Override the get_queryset method because of we can get what we want.
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs): # This method allows us to provide some additional context to the template. 
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)   # Grab this user. This should give us each time a user.
        profile = Profile.objects.get(user=user) # Grab the profile once we get the user.
        
        rel_r = Relationship.objects.filter(sender=profile)   # Relationship receiver where we are going to simply query relationships by the sender equal to our profile. Here we are storing relationships where we invited other users to friends. 
        rel_s = Relationship.objects.filter(receiver=profile)  # Relationship sender where we are going to simply query relationships by the receiver equal to our profile.        
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user) # receiver is relate to the user.
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver 
        context['rel_sender'] = rel_sender 
        
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        return context


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'profiles/profile_detail.html'
    
    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs): # This method allows us to provide some additional context to the template. 
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)   # Grab this user. This should give us each time a user.
        profile = Profile.objects.get(user=user) # Grab the profile once we get the user.
        rel_r = Relationship.objects.filter(sender=profile)   # Relationship receiver where we are going to simply query relationships by the sender equal to our profile. Here we are storing relationships where we invited other users to friends. 
        rel_s = Relationship.objects.filter(receiver=profile)  # Relationship sender where we are going to simply query relationships by the receiver equal to our profile.        
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user) # receiver is relate to the user.
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver 
        context['rel_sender'] = rel_sender 
        context['posts'] = self.get_object().get_all_authors_posts()   # Get all the post of this particular profile. get_all_authors_posts from models.py file.
        context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False
        return context


@login_required
def send_invitations(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')  # profile_pk is the name of input field inside the form into html.
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')


@login_required
def remove_from_friends(request):  # Also write some code in signals.
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')  # profile_pk is the name of input field inside the form into html.
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')

profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}

{% if is_empty %}
    <h1>No invitations here...</h1>
{% endif %}
        
<div class="ui grid centered">
    <div class="row">
        {% for obj in qs %}
            <div class="ui segment fluid" style="margin: 4px;">
                <div class="three wide column">
                    <img class="ui small circular image centered" src="{{ obj.avatar.url }}" alt="">
                </div>
                <div class="thirteen wide column">
                    <h3>{{ obj.user }}</h3>
                    <p>{{ obj.bio }}</p>
                    <br>
                    <a href="{{ obj.get_absolute_url }}">
                        <button class="ui primary button w-big mb-5">See profile</button>
                    </a>

                    <!-- Accepting the invitations form -->
                    <form action="{% url 'profiles:accept-invite' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                        <button type="submit" class="ui positive basic button mb-5 w-big"><i class="check icon"></i>Accept invite</button>
                    </form>

                    <!-- Rejecting the invitations form -->
                    <form action="{% url 'profiles:reject-invite' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                        <button type="submit" class="ui negative basic button mb-5 w-big"><i class="close icon"></i>Reject invite</button>
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}

{% block title %}
My Profile
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="ui modal mymodal">
    <i class="close icon"></i>
    <div class="header">
        Update your Profile
    </div>
    <div class="image content">
        <div class="ui medium image">
        <img src="{{ profile.avatar.url }}">
        </div>
        <div class="description">
        <div class="ui header">Provide some additional/newest info about you.</div>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
        
        </div>
    </div>
    <div class="actions">
        <!-- <div class="ui black deny button">
        Nope
        </div> -->
        <button type="submit" class="ui positive right labeled icon button">
        Update
        <i class="checkmark icon"></i>
        </button>
    </form>
    </div>
</div>

<div class="ui segment">
    {% if confirm %}
        <div class="ui green message">Your profile has been updated</div>
    {% endif %}
    <h3>My profile: {{ request.user }} </h3>
    <div class="ui grid">
        <div class="row">
            <div class="six wide column">
                <img class="ui medium rounded image" src="{{ profile.avatar.url }}" alt="{{request.uer}}" srcset="">
                <div class="row mt-5">
                    <button class="ui secondary button" id="modal-btn">Update your profile</button>
                </div>
            </div>
            <div class="ten wide column">
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>Username</td>
                            <td>{{ profile.user }}</td>
                        </tr>
                        <tr>
                            <td>First Name</td>
                            <td>{{ profile.first_name }}</td>
                        </tr>
                        <tr>
                            <td>Last Name</td>
                            <td>{{ profile.last_name }}</td>
                        </tr>
                        <tr>
                            <td>Bio</td>
                            <td>{{ profile.bio }}</td>
                        </tr>
                        <tr>
                            <td>Number of Friends</td>
                            <td>{{ profile.get_friends_no }}</td>
                        </tr>
                        <tr>
                            <td>Friends List</td>
                            <td>
                                <!-- <ul>
                                    {% for friend in profile.get_friends %}
                                    <p>{{ friend }}</p>
                                    {% endfor %}
                                </ul> -->
                                <div class="ui list">
                                    {% for friend in profile.get_friends %}
                                        <div class="item">
                                        <!-- <img class="ui avatar image" src="#"> -->
                                        <div class="content">
                                            <a class="header">{{ friend }}</a>
                                        </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>Number of Posts</td>
                            <td>{{ profile.get_posts_no }}</td>
                        </tr>
                        <tr>
                            <td>Number of Likes Given</td>
                            <td>{{ profile.get_likes_given_no }}</td>
                        </tr>
                        <tr>
                            <td>Number of Likes Received</td>
                            <td>{{ profile.get_likes_received_no }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}









{% comment %}
<h1>My Profile: {{ profile }}</h1>
<hr>
<img src="{{ profile.avatar.url }}" alt="avatar" srcset="">
<br>
{{ profile.avatar.url }}
<br>
{{ profile.avatar }}
<hr>
{{ profile.first_name }}
<br>
{{ profile.last_name }}
<br>
{{ profile.bio }}
<br>
{{ profile.country }}
<br>
Friends Number: {{ profile.get_friends_no }}
<br>
<ul>
    {% for friend in profile.get_friends %}
        <li>{{ friend }}</li>
    {% endfor %}
</ul>
<br>
{% endcomment %}

profiles/templates/profiles/profile_detail.html
{% extends 'base.html' %}

{% block title %}
Profile detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <!-- {{ object }} -->
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src="{{ object.avatar.url }}" alt="">
            <h1>{{ object.user }}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ object.get_posts_no }}</div>
                </div>
                <div class="item">
                    Likes Given
                    <div class="ui label">{{ object.get_likes_given_no }}</div>
                </div>
                <div class="item">
                    Likes Received
                    <div class="ui label">{{ object.get_likes_received_no }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ object.get_friends_no }}</div>
                </div>
            </div>

        <!-- Adding to friends. Sending invitations. form -->
            <!-- First case -->
            {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url 'profiles:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value="{{object.pk}}">
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                </form>
            {% endif %}

            <!-- Second case -->
            {% if object.user in rel_receiver and request.user not in object.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
            {% endif %}

        <!-- Removing from friends form -->
            <!-- Third case -->
            {% if request.user in object.friends.all %}
                <form action="{% url 'profiles:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value="{{object.pk}}">
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                </form>
            {% endif %}

        </div>
        <div class="twelve wide column">
            {% if len_posts %}
                <div class="ui three column grid">
                    {% for post in posts %}
                        <div class="column">
                            <div class="ui segment">
                                <p style="font-weight: bolder; color: #752975;">{{ post.content }}</p>
                                <img src="{{post.image.url}}" class='ui small image'>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <h1>No posts of this user .....</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}
{% if is_empty %}
    <h1>No Profiles</h1>
{% endif %}
<div class="ui grid container" style="padding-left:3%;">
    <div class="row">
        {% for obj in object_list %}
            <div class="ui segment" style="margin: 4px;">
                <div class="three wide column">
                    <img class="ui small circular image centered" src="{{ obj.avatar.url }}" alt="{{ obj.user }}" >
                </div>

                <div class="thirteen wide column">
                    <h3>{{ obj.user }}</h3>
                    <p>{{ obj.bio }}</p>
                    <a href="{{ obj.get_absolute_url }}"><button class="ui primary button mb-5 w-big">See Profile</button></a>
                    <br>
                
                <!-- Adding to friends. Sending invitations. form -->
                    <!-- First case -->
                    {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                        <form action="{% url 'profiles:send-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                        </form>
                    {% endif %}

                    <!-- Second case -->
                    {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                        <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                    {% endif %}

                <!-- Removing from friends form -->
                    <!-- Third case -->
                    {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove-friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% comment %}
<ul>
    {% for item in qs %}
        <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endcomment %}

profiles/templates/profiles/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
invite friends
{% endblock title %}

{% block content %}

<h1>Available to Send Request</h1>

<!-- <ul>
    {% for item in qs %}
        <li>{{ item }}</li>
    {% endfor %}
</ul> -->

<div class="ui stackable four column grid">
    {% for asr in qs %}
    <div class="column">
        <p>{{ asr }}</p>
        <img class="ui small image images" src="{{ asr.avatar.url }}" alt="">
        <p>{{ asr.first_name }}&nbsp;{{ asr.last_name }}</p>
        <!-- <p>{{ asr.user }}</p> -->
        <p>{{ asr.bio }}</p>
    </div>
    {% endfor %}
</div>
{% endblock content %}