flbook/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView, search

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('search', search, name='search'),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, 
    invites_received_view, 
    invite_profiles_list_view,
    # profiles_list_view, 
    ProfileListView,
    ProfileDetailView,
    send_invitations,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    # path('all-profiles/', profiles_list_view, name='all-profiles-view'),
    path('send-invite/', send_invitations, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', accept_invitation, name='accept-invite'),
    path('my-invites/reject/', reject_invitation, name='reject-invite'),
]

templates/main/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}
  <style type="text/css">

    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }
      .masthead.segment {
        min-height: 350px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }


  </style>

  


{% if user.is_authenticated %}
<!-- Page Contents -->
<div class="pusher">
  <div class="ui inverted vertical center aligned segment" style="background-color: #305194;">

    <!-- <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        {{ hello }}
        <br>
        {{ user }}
      </div>
    </div> -->

    <div class="ui text container">
      <h1 class="ui inverted header">
       !! Welcome &nbsp; {{ user|title }}!!
      </h1>
      <h2>Do whatever you want when you want to.</h2>
      <h2>This Is A Social Network Website. You Can Post Here, Can Make Friends Here, Etc.....</h2>
      <div class="ui huge primary button"><a href="{% url 'posts:main-post-view' %}" style="color: beige;">Get Started <i class="right arrow icon"></i></a></div>
    </div>

  </div>

  <div class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        <div class="eight wide column">
            <h1 style="color: rgb(223, 178, 55);">I am {{user_obj.first_name}}&nbsp;{{user_obj.last_name}}. If anyone wants to be a friend of mine, Send me a request.</h1>
            <h3 style="color: rgb(68, 114, 116);">You can contact me - <span style="color: rgb(134, 13, 134);">{{user_obj.user.email}}</span></h3>
            <h3 style="color: cadetblue;">About Me - {{user_obj.bio}}</h3>
        </div>
        <div class="six wide right floated column">
          <img src="{{picture.url}}" class="ui large bordered rounded image">
        </div>
      </div>
      <div class="row">
        <div class="center aligned column">
          <!-- <a class="ui huge button">Check Them Out</a> -->
        </div>
      </div>
    </div>
  </div>


  <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>"Still Developing!!"</h3>
          <p>I will update it later. Kep your eyes on it!!</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <!-- <img src="assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys -->
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <!-- <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
      <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
      <a class="ui large button">Read More</a> -->
      <h4 class="ui horizontal header divider">
        <!-- <a href="#">Case Studies</a> -->
      </h4>
      <!-- <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
      <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
      <a class="ui large button">I'm Still Quite Interested</a> -->
    </div>
  </div>
</div>
{% else %}

<!-- Page Contents -->
<div class="pusher">
  <div class="ui inverted vertical center aligned segment" style="background-color: #305194;">

    <!-- <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        {{ hello }}
        <br>
        {{ user }}
      </div>
    </div> -->

    <div class="ui text container">
      <h1 class="ui inverted header">
       !! Welcome To FLBook !!
      </h1>
      <h2>Do whatever you want when you want to.</h2>
      <h2>This Is A Social Network Website. You Can Post Here, Can Make Friends Here, Etc.....</h2>
      <div class="ui huge primary button"><a href="{% url 'account_login' %}" style="color: beige;">Login To See <i class="right arrow icon"></i></a></div>
    </div>

  </div>

  <div class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        <div class="eight wide column">
            <h1 style="color: rgb(223, 178, 55);">If anyone wants to make Friends, Send a request to each other.</h1>
        </div>
        <div class="six wide right floated column">
          {% load static %}
          <img src="{% static 'images/simg.png' %}" class="ui large bordered rounded image">
        </div>
      </div>
      <div class="row">
        <div class="center aligned column">
          <!-- <a class="ui huge button">Check Them Out</a> -->
        </div>
      </div>
    </div>
  </div>


  <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>"Still Developing!!"</h3>
          <p>I will update it later. Kep your eyes on it!!</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <!-- <img src="assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys -->
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <!-- <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
      <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
      <a class="ui large button">Read More</a> -->
      <h4 class="ui horizontal header divider">
        <!-- <a href="#">Case Studies</a> -->
      </h4>
      <!-- <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
      <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
      <a class="ui large button">I'm Still Quite Interested</a> -->
    </div>
  </div>


</div>
{% endif %}

{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function () {
        console.log('Working')
    })
</script>
{% endblock scripts %}

templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}



<div class="ui inverted menu nav mb-7">
    <div class="ui container">
      <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
          <h3>FLBook</h3>
      </a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item" id="nav_item">
          Board
      </a>
      {% endif %}
  
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <div class="item">
              <div class="ui floating dropdown icon button teal" id="nav_drop"> Friends
                  <i class="dropdown icon"></i>
                  <div class="menu" style="background-color: #1A202C;">
                      <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item" id="drop_item">
                          All Profiles
                      </a>
                      <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item" id="drop_item">
                          Send Invites
                      </a>
                      <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item" id="drop_item">
                          Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                      </a>
                  </div>
               </div>
          </div>
               <div class="item" >
                    <form action="{% url 'posts:search' %}" method="GET">
                        <div class="ui action left icon input" style="color: rgb(108, 234, 243);">
                            <input class="prompt" type="text" id="query" name='q' placeholder="name of a friend..." style="background-color: #2D3748 !important; color: rgb(108, 234, 243);">
                            <i class="search icon"></i>
                            <button type='submit' class="ui button" style="background-color: #233046 !important; color: rgb(108, 234, 243);">Search</button>
                        </div>
                    </form>
              </div>
          
              <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item" id="nav_item">
                  <img src="{{picture.url}}" class='ui avatar image'>&nbsp;  <!-- picture from context_processors -->
                   {{ request.user }}
              </a>
  
              <a href="{% url 'account_logout' %}" class="ui item"  id="nav_item">
                  Logout
              </a>
          {% else %}
          <a href="{% url 'account_login' %}" class="ui item"  id="nav_item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>